config/routes.rb
Rails.application.routes.draw do
  resources :datos
  resources :sus_datos
  resources :mi_tareas

end

app/models/dato.rb
class Dato < ActiveRecord::Base
end

app/models/mi_tarea.rb
class MiTarea < ActiveRecord::Base
end

app/models/sus_dato.rb
class SusDato < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/datos_controller.rb
class DatosController < ApplicationController
  before_action :set_dato, only: [:show, :edit, :update, :destroy]

  # GET /datos
  # GET /datos.json
  def index
    @datos = Dato.all
  end

  # GET /datos/1
  # GET /datos/1.json
  def show
  end

  # GET /datos/new
  def new
    @dato = Dato.new
  end

  # GET /datos/1/edit
  def edit
  end

  # POST /datos
  # POST /datos.json
  def create
    @dato = Dato.new(dato_params)

    respond_to do |format|
      if @dato.save
        format.html { redirect_to @dato, notice: 'Dato was successfully created.' }
        format.json { render :show, status: :created, location: @dato }
      else
        format.html { render :new }
        format.json { render json: @dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datos/1
  # PATCH/PUT /datos/1.json
  def update
    respond_to do |format|
      if @dato.update(dato_params)
        format.html { redirect_to @dato, notice: 'Dato was successfully updated.' }
        format.json { render :show, status: :ok, location: @dato }
      else
        format.html { render :edit }
        format.json { render json: @dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datos/1
  # DELETE /datos/1.json
  def destroy
    @dato.destroy
    respond_to do |format|
      format.html { redirect_to datos_url, notice: 'Dato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dato
      @dato = Dato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dato_params
      params.require(:dato).permit(:Fecha, :Nombre, :Edad, :Direccion, :Comer_o, :Dormir)
    end
end

app/controllers/mi_tareas_controller.rb
class MiTareasController < ApplicationController
  before_action :set_mi_tarea, only: [:show, :edit, :update, :destroy]

  # GET /mi_tareas
  # GET /mi_tareas.json
  def index
    @mi_tareas = MiTarea.all
  end

  # GET /mi_tareas/1
  # GET /mi_tareas/1.json
  def show
  end

  # GET /mi_tareas/new
  def new
    @mi_tarea = MiTarea.new
  end

  # GET /mi_tareas/1/edit
  def edit
  end

  # POST /mi_tareas
  # POST /mi_tareas.json
  def create
    @mi_tarea = MiTarea.new(mi_tarea_params)

    respond_to do |format|
      if @mi_tarea.save
        format.html { redirect_to @mi_tarea, notice: 'Mi tarea was successfully created.' }
        format.json { render :show, status: :created, location: @mi_tarea }
      else
        format.html { render :new }
        format.json { render json: @mi_tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mi_tareas/1
  # PATCH/PUT /mi_tareas/1.json
  def update
    respond_to do |format|
      if @mi_tarea.update(mi_tarea_params)
        format.html { redirect_to @mi_tarea, notice: 'Mi tarea was successfully updated.' }
        format.json { render :show, status: :ok, location: @mi_tarea }
      else
        format.html { render :edit }
        format.json { render json: @mi_tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mi_tareas/1
  # DELETE /mi_tareas/1.json
  def destroy
    @mi_tarea.destroy
    respond_to do |format|
      format.html { redirect_to mi_tareas_url, notice: 'Mi tarea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mi_tarea
      @mi_tarea = MiTarea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mi_tarea_params
      params.require(:mi_tarea).permit(:Fecha, :Nombre, :Edad, :Direccion, :Comer, :Dormir)
    end
end

app/controllers/sus_datos_controller.rb
class SusDatosController < ApplicationController
  before_action :set_sus_dato, only: [:show, :edit, :update, :destroy]

  # GET /sus_datos
  # GET /sus_datos.json
  def index
    @sus_datos = SusDato.all
  end

  # GET /sus_datos/1
  # GET /sus_datos/1.json
  def show
  end

  # GET /sus_datos/new
  def new
    @sus_dato = SusDato.new
  end

  # GET /sus_datos/1/edit
  def edit
  end

  # POST /sus_datos
  # POST /sus_datos.json
  def create
    @sus_dato = SusDato.new(sus_dato_params)

    respond_to do |format|
      if @sus_dato.save
        format.html { redirect_to @sus_dato, notice: 'Sus dato was successfully created.' }
        format.json { render :show, status: :created, location: @sus_dato }
      else
        format.html { render :new }
        format.json { render json: @sus_dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sus_datos/1
  # PATCH/PUT /sus_datos/1.json
  def update
    respond_to do |format|
      if @sus_dato.update(sus_dato_params)
        format.html { redirect_to @sus_dato, notice: 'Sus dato was successfully updated.' }
        format.json { render :show, status: :ok, location: @sus_dato }
      else
        format.html { render :edit }
        format.json { render json: @sus_dato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sus_datos/1
  # DELETE /sus_datos/1.json
  def destroy
    @sus_dato.destroy
    respond_to do |format|
      format.html { redirect_to sus_datos_url, notice: 'Sus dato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sus_dato
      @sus_dato = SusDato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sus_dato_params
      params.require(:sus_dato).permit(:Fecha, :Nombre, :Edad, :Direccion, :Comer, :Dormir)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datos_helper.rb
module DatosHelper
end

app/helpers/mi_tareas_helper.rb
module MiTareasHelper
end

app/helpers/sus_datos_helper.rb
module SusDatosHelper
end

app/views/datos/_form.html.erb
<%= form_for(@dato) do |f| %>
  <% if @dato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dato.errors.count, "error") %> prohibited this dato from being saved:</h2>

      <ul>
      <% @dato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Fecha %><br>
    <%= f.datetime_select :Fecha %>
  </div>
  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :Edad %><br>
    <%= f.number_field :Edad %>
  </div>
  <div class="field">
    <%= f.label :Direccion %><br>
    <%= f.text_area :Direccion %>
  </div>
  <div class="field">
    <%= f.label :Comer_o %><br>
    <%= f.check_box :Comer_o %>
  </div>
  <div class="field">
    <%= f.label :Dormir %><br>
    <%= f.check_box :Dormir %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/datos/edit.html.erb
<h1>Editing Dato</h1>

<%= render 'form' %>

<%= link_to 'Show', @dato %> |
<%= link_to 'Back', datos_path %>

app/views/datos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Datos</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Direccion</th>
      <th>Comer o</th>
      <th>Dormir</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @datos.each do |dato| %>
      <tr>
        <td><%= dato.Fecha %></td>
        <td><%= dato.Nombre %></td>
        <td><%= dato.Edad %></td>
        <td><%= dato.Direccion %></td>
        <td><%= dato.Comer_o %></td>
        <td><%= dato.Dormir %></td>
        <td><%= link_to 'Show', dato %></td>
        <td><%= link_to 'Edit', edit_dato_path(dato) %></td>
        <td><%= link_to 'Destroy', dato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dato', new_dato_path %>

app/views/datos/new.html.erb
<h1>New Dato</h1>

<%= render 'form' %>

<%= link_to 'Back', datos_path %>

app/views/datos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @dato.Fecha %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @dato.Nombre %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @dato.Edad %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @dato.Direccion %>
</p>

<p>
  <strong>Comer o:</strong>
  <%= @dato.Comer_o %>
</p>

<p>
  <strong>Dormir:</strong>
  <%= @dato.Dormir %>
</p>

<%= link_to 'Edit', edit_dato_path(@dato) %> |
<%= link_to 'Back', datos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tarea2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>